extern int virtualnumberpad;
extern int letterx;
extern int lettery;
extern int kbletterx;
extern int kblettery;
extern int shiftpressed;
extern int numberpadnumber;
extern char romfilenamecopy[999];
//extern *configfile;
//extern char gamename[64];
extern crc32;
extern int drawmenu;
extern int menu_overlayposition;
extern int menu_sound;
extern int menu_transparency;
extern int menu_customoverlays;
extern int selectedoption;
extern int displaycontrolinfo;
extern int displayplayer2;
