;; This file was autogenerated.
;;
;; The author of the generating program, Joseph Zbiciak
;; hereby puts both the generator and its output in the
;; public domain.  The data below is therefore public domain.
;;
;; You can compare the computed frequencies versus the ideal
;; values using this chart online:
;;     http://www.phy.mtu.edu/~suits/notefreqs.html


NOTES.NTSC  PROC
@@C1        DECLE   $0D5C   ; C1           32.71 Hz (+0.014% err)
@@Db1
@@Cs1       DECLE   $0C9D   ; C#1 / Db1    34.64 Hz (-0.015% err)
@@D1        DECLE   $0BE7   ; D1           36.71 Hz (+0.010% err)
@@Eb1
@@Ds1       DECLE   $0B3C   ; D#1 / Eb1    38.89 Hz (+0.010% err)
@@E1        DECLE   $0A9B   ; E1           41.20 Hz (-0.006% err)
@@F1        DECLE   $0A02   ; F1           43.66 Hz (+0.018% err)
@@Gb1
@@Fs1       DECLE   $0973   ; F#1 / Gb1    46.24 Hz (-0.015% err)
@@G1        DECLE   $08EB   ; G1           49.00 Hz (-0.004% err)
@@Ab1
@@Gs1       DECLE   $086B   ; G#1 / Ab1    51.91 Hz (-0.011% err)
@@A1        DECLE   $07F2   ; A1           55.00 Hz (-0.008% err)
@@Bb1
@@As1       DECLE   $0780   ; A#1 / Bb1    58.26 Hz (-0.017% err)
@@B1        DECLE   $0714   ; B1           61.73 Hz (-0.003% err)
@@C2        DECLE   $06AE   ; C2           65.42 Hz (+0.014% err)
@@Db2
@@Cs2       DECLE   $064E   ; C#2 / Db2    69.31 Hz (+0.016% err)
@@D2        DECLE   $05F4   ; D2           73.40 Hz (-0.023% err)
@@Eb2
@@Ds2       DECLE   $059E   ; D#2 / Eb2    77.79 Hz (+0.010% err)
@@E2        DECLE   $054D   ; E2           82.43 Hz (+0.031% err)
@@F2        DECLE   $0501   ; F2           87.32 Hz (+0.018% err)
@@Gb2
@@Fs2       DECLE   $04B9   ; F#2 / Gb2    92.52 Hz (+0.027% err)
@@G2        DECLE   $0475   ; G2           98.04 Hz (+0.039% err)
@@Ab2
@@Gs2       DECLE   $0435   ; G#2 / Ab2   103.86 Hz (+0.036% err)
@@A2        DECLE   $03F9   ; A2          109.99 Hz (-0.008% err)
@@Bb2
@@As2       DECLE   $03C0   ; A#2 / Bb2   116.52 Hz (-0.017% err)
@@B2        DECLE   $038A   ; B2          123.47 Hz (-0.003% err)
@@C3        DECLE   $0357   ; C3          130.83 Hz (+0.014% err)
@@Db3
@@Cs3       DECLE   $0327   ; C#3 / Db3   138.61 Hz (+0.016% err)
@@D3        DECLE   $02FA   ; D3          146.80 Hz (-0.023% err)
@@Eb3
@@Ds3       DECLE   $02CF   ; D#3 / Eb3   155.58 Hz (+0.010% err)
@@E3        DECLE   $02A7   ; E3          164.74 Hz (-0.043% err)
@@F3        DECLE   $0281   ; F3          174.51 Hz (-0.060% err)
@@Gb3
@@Fs3       DECLE   $025D   ; F#3 / Gb3   184.89 Hz (-0.056% err)
@@G3        DECLE   $023B   ; G3          195.90 Hz (-0.048% err)
@@Ab3
@@Gs3       DECLE   $021B   ; G#3 / Ab3   207.53 Hz (-0.057% err)
@@A3        DECLE   $01FC   ; A3          220.20 Hz (+0.090% err)
@@Bb3
@@As3       DECLE   $01E0   ; A#3 / Bb3   233.04 Hz (-0.017% err)
@@B3        DECLE   $01C5   ; B3          246.93 Hz (-0.003% err)
@@C4        DECLE   $01AC   ; C4          261.36 Hz (-0.103% err)
@@Db4
@@Cs4       DECLE   $0194   ; C#4 / Db4   276.88 Hz (-0.108% err)
@@D4        DECLE   $017D   ; D4          293.60 Hz (-0.023% err)
@@Eb4
@@Ds4       DECLE   $0168   ; D#4 / Eb4   310.72 Hz (-0.129% err)
@@E4        DECLE   $0153   ; E4          329.97 Hz (+0.105% err)
@@F4        DECLE   $0140   ; F4          349.56 Hz (+0.096% err)
@@Gb4
@@Fs4       DECLE   $012E   ; F#4 / Gb4   370.40 Hz (+0.110% err)
@@G4        DECLE   $011D   ; G4          392.49 Hz (+0.127% err)
@@Ab4
@@Gs4       DECLE   $010D   ; G#4 / Ab4   415.84 Hz (+0.129% err)
@@A4        DECLE   $00FE   ; A4          440.40 Hz (+0.090% err)
@@Bb4
@@As4       DECLE   $00F0   ; A#4 / Bb4   466.09 Hz (-0.017% err)
@@B4        DECLE   $00E2   ; B4          494.96 Hz (+0.218% err)
@@C5        DECLE   $00D6   ; C5          522.71 Hz (-0.103% err)
@@Db5
@@Cs5       DECLE   $00CA   ; C#5 / Db5   553.77 Hz (-0.108% err)
@@D5        DECLE   $00BE   ; D5          588.74 Hz (+0.240% err)
@@Eb5
@@Ds5       DECLE   $00B4   ; D#5 / Eb5   621.45 Hz (-0.129% err)
@@E5        DECLE   $00AA   ; E5          658.00 Hz (-0.190% err)
@@F5        DECLE   $00A0   ; F5          699.13 Hz (+0.096% err)
@@Gb5
@@Fs5       DECLE   $0097   ; F#5 / Gb5   740.80 Hz (+0.110% err)
@@G5        DECLE   $008F   ; G5          782.24 Hz (-0.223% err)
@@Ab5
@@Gs5       DECLE   $0087   ; G#5 / Ab5   828.60 Hz (-0.242% err)
@@A5        DECLE   $007F   ; A5          880.79 Hz (+0.090% err)
@@Bb5
@@As5       DECLE   $0078   ; A#5 / Bb5   932.17 Hz (-0.017% err)
@@B5        DECLE   $0071   ; B5          989.92 Hz (+0.218% err)
@@C6        DECLE   $006B   ; C6         1045.43 Hz (-0.103% err)
@@Db6
@@Cs6       DECLE   $0065   ; C#6 / Db6  1107.53 Hz (-0.108% err)
@@D6        DECLE   $005F   ; D6         1177.48 Hz (+0.240% err)
@@Eb6
@@Ds6       DECLE   $005A   ; D#6 / Eb6  1242.90 Hz (-0.129% err)
@@E6        DECLE   $0055   ; E6         1316.01 Hz (-0.190% err)
@@F6        DECLE   $0050   ; F6         1398.26 Hz (+0.096% err)
@@Gb6
@@Fs6       DECLE   $004C   ; F#6 / Gb6  1471.85 Hz (-0.549% err)
@@G6        DECLE   $0047   ; G6         1575.50 Hz (+0.480% err)
@@Ab6
@@Gs6       DECLE   $0043   ; G#6 / Ab6  1669.56 Hz (+0.502% err)
@@A6        DECLE   $0040   ; A6         1747.82 Hz (-0.692% err)
@@Bb6
@@As6       DECLE   $003C   ; A#6 / Bb6  1864.35 Hz (-0.017% err)
@@B6        DECLE   $0039   ; B6         1962.47 Hz (-0.661% err)
@@C7        DECLE   $0035   ; C7         2110.58 Hz (+0.840% err)
@@Db7
@@Cs7       DECLE   $0032   ; C#7 / Db7  2237.22 Hz (+0.891% err)
@@D7        DECLE   $0030   ; D7         2330.43 Hz (-0.804% err)
@@Eb7
@@Ds7       DECLE   $002D   ; D#7 / Eb7  2485.80 Hz (-0.129% err)
@@E7        DECLE   $002A   ; E7         2663.35 Hz (+0.999% err)
@@F7        DECLE   $0028   ; F7         2796.52 Hz (+0.096% err)
@@Gb7
@@Fs7       DECLE   $0026   ; F#7 / Gb7  2943.70 Hz (-0.549% err)
@@G7        DECLE   $0024   ; G7         3107.24 Hz (-0.916% err)
@@Ab7
@@Gs7       DECLE   $0022   ; G#7 / Ab7  3290.02 Hz (-0.976% err)
@@A7        DECLE   $0020   ; A7         3495.65 Hz (-0.692% err)
@@Bb7
@@As7       DECLE   $001E   ; A#7 / Bb7  3728.69 Hz (-0.017% err)
@@B7        DECLE   $001C   ; B7         3995.03 Hz (+1.113% err)
@@C8        DECLE   $001B   ; C8         4142.99 Hz (-1.028% err)
            ENDP


NOTES.PAL   PROC
@@C1        DECLE   $0EEE   ; C1           32.71 Hz (+0.007% err)
@@Db1
@@Cs1       DECLE   $0E18   ; C#1 / Db1    34.65 Hz (-0.007% err)
@@D1        DECLE   $0D4D   ; D1           36.71 Hz (+0.007% err)
@@Eb1
@@Ds1       DECLE   $0C8E   ; D#1 / Eb1    38.89 Hz (+0.004% err)
@@E1        DECLE   $0BDA   ; E1           41.20 Hz (-0.009% err)
@@F1        DECLE   $0B2F   ; F1           43.66 Hz (+0.016% err)
@@Gb1
@@Fs1       DECLE   $0A8F   ; F#1 / Gb1    46.24 Hz (-0.009% err)
@@G1        DECLE   $09F7   ; G1           49.00 Hz (+0.002% err)
@@Ab1
@@Gs1       DECLE   $0968   ; G#1 / Ab1    51.91 Hz (-0.005% err)
@@A1        DECLE   $08E1   ; A1           54.99 Hz (-0.012% err)
@@Bb1
@@As1       DECLE   $0861   ; A#1 / Bb1    58.28 Hz (+0.008% err)
@@B1        DECLE   $07E9   ; B1           61.73 Hz (-0.011% err)
@@C2        DECLE   $0777   ; C2           65.41 Hz (+0.007% err)
@@Db2
@@Cs2       DECLE   $070C   ; C#2 / Db2    69.29 Hz (-0.007% err)
@@D2        DECLE   $06A7   ; D2           73.40 Hz (-0.022% err)
@@Eb2
@@Ds2       DECLE   $0647   ; D#2 / Eb2    77.78 Hz (+0.004% err)
@@E2        DECLE   $05ED   ; E2           82.40 Hz (-0.009% err)
@@F2        DECLE   $0598   ; F2           87.29 Hz (-0.019% err)
@@Gb2
@@Fs2       DECLE   $0547   ; F#2 / Gb2    92.52 Hz (+0.028% err)
@@G2        DECLE   $04FC   ; G2           97.96 Hz (-0.037% err)
@@Ab2
@@Gs2       DECLE   $04B4   ; G#2 / Ab2   103.82 Hz (-0.005% err)
@@A2        DECLE   $0470   ; A2          110.04 Hz (+0.032% err)
@@Bb2
@@As2       DECLE   $0431   ; A#2 / Bb2   116.50 Hz (-0.039% err)
@@B2        DECLE   $03F4   ; B2          123.52 Hz (+0.038% err)
@@C3        DECLE   $03BC   ; C3          130.75 Hz (-0.046% err)
@@Db3
@@Cs3       DECLE   $0386   ; C#3 / Db3   138.58 Hz (-0.007% err)
@@D3        DECLE   $0353   ; D3          146.89 Hz (+0.037% err)
@@Eb3
@@Ds3       DECLE   $0324   ; D#3 / Eb3   155.47 Hz (-0.058% err)
@@E3        DECLE   $02F6   ; E3          164.91 Hz (+0.057% err)
@@F3        DECLE   $02CC   ; F3          174.58 Hz (-0.019% err)
@@Gb3
@@Fs3       DECLE   $02A4   ; F#3 / Gb3   184.91 Hz (-0.046% err)
@@G3        DECLE   $027E   ; G3          195.92 Hz (-0.037% err)
@@Ab3
@@Gs3       DECLE   $025A   ; G#3 / Ab3   207.64 Hz (-0.005% err)
@@A3        DECLE   $0238   ; A3          220.07 Hz (+0.032% err)
@@Bb3
@@As3       DECLE   $0218   ; A#3 / Bb3   233.21 Hz (+0.055% err)
@@B3        DECLE   $01FA   ; B3          247.04 Hz (+0.038% err)
@@C4        DECLE   $01DE   ; C4          261.51 Hz (-0.046% err)
@@Db4
@@Cs4       DECLE   $01C3   ; C#4 / Db4   277.16 Hz (-0.007% err)
@@D4        DECLE   $01AA   ; D4          293.43 Hz (-0.081% err)
@@Eb4
@@Ds4       DECLE   $0192   ; D#4 / Eb4   310.95 Hz (-0.058% err)
@@E4        DECLE   $017B   ; E4          329.82 Hz (+0.057% err)
@@F4        DECLE   $0166   ; F4          349.16 Hz (-0.019% err)
@@Gb4
@@Fs4       DECLE   $0152   ; F#4 / Gb4   369.82 Hz (-0.046% err)
@@G4        DECLE   $013F   ; G4          391.85 Hz (-0.037% err)
@@Ab4
@@Gs4       DECLE   $012D   ; G#4 / Ab4   415.28 Hz (-0.005% err)
@@A4        DECLE   $011C   ; A4          440.14 Hz (+0.032% err)
@@Bb4
@@As4       DECLE   $010C   ; A#4 / Bb4   466.42 Hz (+0.055% err)
@@B4        DECLE   $00FD   ; B4          494.07 Hz (+0.038% err)
@@C5        DECLE   $00EF   ; C5          523.01 Hz (-0.046% err)
@@Db5
@@Cs5       DECLE   $00E1   ; C#5 / Db5   555.56 Hz (+0.215% err)
@@D5        DECLE   $00D5   ; D5          586.85 Hz (-0.081% err)
@@Eb5
@@Ds5       DECLE   $00C9   ; D#5 / Eb5   621.89 Hz (-0.058% err)
@@E5        DECLE   $00BE   ; E5          657.89 Hz (-0.206% err)
@@F5        DECLE   $00B3   ; F5          698.32 Hz (-0.019% err)
@@Gb5
@@Fs5       DECLE   $00A9   ; F#5 / Gb5   739.64 Hz (-0.046% err)
@@G5        DECLE   $009F   ; G5          786.16 Hz (+0.277% err)
@@Ab5
@@Gs5       DECLE   $0096   ; G#5 / Ab5   833.33 Hz (+0.328% err)
@@A5        DECLE   $008E   ; A5          880.28 Hz (+0.032% err)
@@Bb5
@@As5       DECLE   $0086   ; A#5 / Bb5   932.84 Hz (+0.055% err)
@@B5        DECLE   $007F   ; B5          984.25 Hz (-0.356% err)
@@C6        DECLE   $0077   ; C6         1050.42 Hz (+0.374% err)
@@Db6
@@Cs6       DECLE   $0071   ; C#6 / Db6  1106.19 Hz (-0.229% err)
@@D6        DECLE   $006A   ; D6         1179.25 Hz (+0.390% err)
@@Eb6
@@Ds6       DECLE   $0064   ; D#6 / Eb6  1250.00 Hz (+0.441% err)
@@E6        DECLE   $005F   ; E6         1315.79 Hz (-0.206% err)
@@F6        DECLE   $0059   ; F6         1404.49 Hz (+0.543% err)
@@Gb6
@@Fs6       DECLE   $0054   ; F#6 / Gb6  1488.10 Hz (+0.548% err)
@@G6        DECLE   $0050   ; G6         1562.50 Hz (-0.350% err)
@@Ab6
@@Gs6       DECLE   $004B   ; G#6 / Ab6  1666.67 Hz (+0.328% err)
@@A6        DECLE   $0047   ; A6         1760.56 Hz (+0.032% err)
@@Bb6
@@As6       DECLE   $0043   ; A#6 / Bb6  1865.67 Hz (+0.055% err)
@@B6        DECLE   $003F   ; B6         1984.13 Hz (+0.435% err)
@@C7        DECLE   $003C   ; C7         2083.33 Hz (-0.462% err)
@@Db7
@@Cs7       DECLE   $0038   ; C#7 / Db7  2232.14 Hz (+0.662% err)
@@D7        DECLE   $0035   ; D7         2358.49 Hz (+0.390% err)
@@Eb7
@@Ds7       DECLE   $0032   ; D#7 / Eb7  2500.00 Hz (+0.441% err)
@@E7        DECLE   $002F   ; E7         2659.57 Hz (+0.855% err)
@@F7        DECLE   $002D   ; F7         2777.78 Hz (-0.574% err)
@@Gb7
@@Fs7       DECLE   $002A   ; F#7 / Gb7  2976.19 Hz (+0.548% err)
@@G7        DECLE   $0028   ; G7         3125.00 Hz (-0.350% err)
@@Ab7
@@Gs7       DECLE   $0026   ; G#7 / Ab7  3289.47 Hz (-0.992% err)
@@A7        DECLE   $0024   ; A7         3472.22 Hz (-1.357% err)
@@Bb7
@@As7       DECLE   $0022   ; A#7 / Bb7  3676.47 Hz (-1.417% err)
@@B7        DECLE   $0020   ; B7         3906.25 Hz (-1.134% err)
@@C8        DECLE   $001E   ; C8         4166.67 Hz (-0.462% err)
            ENDP
