# -*- makefile -*-
#
# This file is automatically generated by configure.
# Do not hand edit.

OSTYPE		:= linux-gnu
MACHINETYPE	:= mipsel
PLATFORM	:= mipsel-unknown-linux-gnu
FULLOSTYPE	:= unknown-linux-gnu
