CC=mipsel-linux-gcc
CFLAGS=-O2 -I/opt/mipsel-linux-uclibc/usr/include/ -ffast-math
LIBS=-L/opt/mipsel-linux-uclibc/usr/lib/ -lSDL -lSDL_mixer

just4qix: main.o render.o update.o input.o sound.o particle.o
	$(CC) main.o render.o update.o input.o sound.o particle.o -o just4qix -lSDL -lSDL_mixer

clean:
	rm *.o
	rm just4qix
