./test_liste.out
./test_pierre.out
./test_liste_pierre.out
./test_ennemi.out
./test_liste_ennemi.out
./test_joueur.out
./test_liste_joueur.out
./test_diamant.out
./test_liste_diamant.out
./test_explosion.out
./test_liste_explosion.out
./test_niveau.out
